### 하나의 파일 제출이라 책기준 위에서부터 1번으로 해서 묶었음
### 각 단계별 구분을 위해 변수명을 1, 1a와 같은 방식으로 최대한 가독성 좋게 표기하였음 
1.

In [22]:
import numpy as np
import pandas as pd

In [4]:
array1_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array1_1.ndim)

3


In [5]:
array1_2 = np.array([10, 20, 30, 40, 50, 60])
reshaped1_2 = array1_2.reshape(2, 3)

print(reshaped1_2)

[[10 20 30]
 [40 50 60]]


In [6]:
array1_3 = np.array([7, 14, 21])
new_array1_3 = array1_3[:, np.newaxis]

print("배열 모양:", new_array1_3.shape)
print("최종 차원 수:", new_array1_3.ndim)

배열 모양: (3, 1)
최종 차원 수: 2


2. 

In [7]:
array2_1 = np.array([[1, 2, 3], [4, 5, 6]])

print(array2_1.shape)

(2, 3)


In [8]:
array2_2 = np.array([10, 20, 30, 40, 50, 60])
reshaped2_2 = array2_2.reshape(2, 3)

print(reshaped2_2.shape)

(2, 3)


In [9]:
array2_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped2_3 = array2_3.reshape(3, 2, 2)

print(reshaped2_3.shape)

(3, 2, 2)


3.

In [10]:
array3_1 = np.array([10, 20, 30])

print(array3_1.dtype)

int64


In [55]:
array3_2 = np.array([1, 2, 3])
converted3_2 = array3_2.astype(float) 

print(converted3_2.dtype)

float64


In [12]:
array3_3 = np.array([100, 200, 300])
converted3_3 = array3_3.astype(np.uint8)

print(converted3_3.nbytes)

3


4.

In [13]:
array4_1 = np.array([10, 20, 30, 40, 50])

print("첫 번째 요소:", array4_1[0])
print("마지막 요소:", array4_1[-1])

첫 번째 요소: 10
마지막 요소: 50


In [14]:
matrix4_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("첫 번째 열:", matrix4_2[:, 0])
print("두 번째 행:", matrix4_2[1, :])

첫 번째 열: [1 4 7]
두 번째 행: [4 5 6]


In [15]:
array4_3 = np.array([5, 15, 8, 20, 3, 12])
print(np.where(array4_3 > 10))

(array([1, 3, 5]),)


5.

In [16]:
a5_1 = np.array([1, 2, 3])
b5_1 = np.array([4, 5, 6])

print(a5_1 + b5_1)

[5 7 9]


In [17]:
matrix5_2 = np.array([[10, 20, 30], [40, 50, 60]])
vector5_2 = np.array([1, 2, 3])

print(matrix5_2 + vector5_2)

[[11 22 33]
 [41 52 63]]


In [18]:
array5_3 = np.array([[3, 7, 2], [8, 4, 6]])
max_axis = array5_3.max(axis=0) 

print("최댓값:", max_axis)
print("최종 차원:", max_axis.ndim)

최댓값: [8 7 6]
최종 차원: 1


6. 

In [19]:
array6_1 = np.array([1, 2, 3, 4])

print(np.square(array6_1))

[ 1  4  9 16]


In [20]:
array6_2a = np.array([10, 20, 30])
array6_2b = np.array([1, 2, 3])

np.add(array6_2a, array6_2b, out=array6_2a)
print(array6_2a)

[11 22 33]


In [27]:
array6_3 = np.array([1, np.e, 10, 100])
values = np.log(array6_3)

print(values[values > 1])

[2.30258509 4.60517019]


7. 

In [23]:
series7_1 = pd.Series([5, 10, 15, 20])

print(series7_1.index)

RangeIndex(start=0, stop=4, step=1)


In [24]:
data7_2 = {'a': 100, 'b': 200, 'c': 300}
series7_2 = pd.Series(data7_2)

print(series7_2['b'])

200


In [26]:
series7_3 = pd.Series([1, 2, None, 4, None, 6])

print("결측치 여부:\n", series7_3.isna())
series7_3 = series7_3.fillna(0)
print("Series:\n", series7_3)

결측치 여부:
 0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool
Series:
 0    1.0
1    2.0
2    0.0
3    4.0
4    0.0
5    6.0
dtype: float64


8.

In [29]:
data8_1 = {
    '이름': ['홍길동', '김철수', '박영희'],
    '나이': [25, 30, 28],
    '성별': ['남', '남', '여']
}
df8_1 = pd.DataFrame(data8_1)

print(df8_1.columns)

Index(['이름', '나이', '성별'], dtype='str')


In [28]:
data8_2 = {
    '이름': ['홍길동', '김철수', '박영희'],
    '나이': [25, 30, 28],
    '성별': ['남', '남', '여']
}
df8_2 = pd.DataFrame(data8_2)
df8_2 = df8_2.sort_values(by='나이', ascending=True)

print(df8_2)

    이름  나이 성별
0  홍길동  25  남
2  박영희  28  여
1  김철수  30  남


In [31]:
data8_3 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신'],
    '국어': [85, 90, 88, 92],
    '영어': [78, 85, 89, 87],
    '수학': [92, 88, 84, 90]
}
df8_3 = pd.DataFrame(data8_3)
df8_3['총점'] = df8_3['국어'] + df8_3['영어'] + df8_3['수학']
df8_3 = df8_3[df8_3['총점'] >= 250]
print(df8_3)

    이름  국어  영어  수학   총점
0  홍길동  85  78  92  255
1  김철수  90  85  88  263
2  박영희  88  89  84  261
3  이순신  92  87  90  269


9.

In [32]:
data9_1 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산']
}
df9_1 = pd.DataFrame(data9_1)

df9_1 = df9_1[df9_1['나이'] >= 30]
print(df9_1)

    이름  나이  도시
1  김철수  30  부산
2  박영희  35  서울
3  이순신  40  대구
4  강감찬  45  부산


In [33]:
data9_2 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산'],
    '점수': [85, 90, 75, 95, 80]
}
df9_2 = pd.DataFrame(data9_2)

df9_2 = df9_2[(df9_2['도시'] == '서울') | (df9_2['점수'] >= 80)]
print(df9_2)

    이름  나이  도시  점수
0  홍길동  25  서울  85
1  김철수  30  부산  90
2  박영희  35  서울  75
3  이순신  40  대구  95
4  강감찬  45  부산  80


In [34]:
data9_3 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산'],
    '점수': [85, 90, 75, 95, 80]
}
df9_3 = pd.DataFrame(data9_3)

df9_3 = df9_3.query("나이 >= 35 and 점수 > 80")
print(df9_3)

    이름  나이  도시  점수
3  이순신  40  대구  95


10. 

In [35]:
data10_1 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신'],
    '부서': ['영업', '영업', '인사', '인사'],
    '급여': [5000, 5500, 4800, 5100]
}
df10_1 = pd.DataFrame(data10_1)

df10_1 = df10_1.groupby('부서')['급여'].sum()
print(df10_1)

부서
영업    10500
인사     9900
Name: 급여, dtype: int64


In [36]:
data10_2 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}
df10_2 = pd.DataFrame(data10_2)

df10_2 = df10_2.groupby('부서')['급여'].agg(['sum', 'mean'])
print(df10_2)

      sum    mean
부서               
IT  12200  6100.0
영업  10500  5250.0
인사   9900  4950.0


In [37]:
data10_3 = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}
df10_3 = pd.DataFrame(data10_3)

df10_3 = df10_3.groupby('부서').filter(lambda x: x['급여'].mean() >= 5000)
print(df10_3)

     이름  부서    급여
0   홍길동  영업  5000
1   김철수  영업  5500
4   강감찬  IT  6000
5  신사임당  IT  6200


11

In [38]:
df11_1a = pd.DataFrame({'고객ID': [1, 2, 3], '이름': ['홍길동', '김철수', '이영희']})
df11_1b = pd.DataFrame({'고객ID': [2, 3, 4], '구매액': [10000, 20000, 30000]})

df11_1a = pd.merge(df11_1a, df11_1b, on='고객ID', how='inner')
print(df11_1a)

   고객ID   이름    구매액
0     2  김철수  10000
1     3  이영희  20000


In [39]:
df11_2a = pd.DataFrame({'고객ID': [1, 2, 3], '이름': ['홍길동', '김철수', '이영희']})
df11_2b = pd.DataFrame({'고객ID': [2, 3, 4], '구매액': [15000, 25000, 35000]})

df11_2a = pd.merge(df11_2a, df11_2b, on='고객ID', how='left')
print(df11_2a)

   고객ID   이름      구매액
0     1  홍길동      NaN
1     2  김철수  15000.0
2     3  이영희  25000.0


In [40]:
df11_3a = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '대전'],
    '구매액': [10000, 20000, 30000]
})
df11_3b = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '광주'],
    '구매액': [15000, 25000, 35000]
})

df11_3a = pd.merge(df11_3a, df11_3b, on=['고객ID', '도시'], how='outer', suffixes=('_left', '_right'))
print(df11_3a)

   고객ID  도시  구매액_left  구매액_right
0     1  서울   10000.0    15000.0
1     2  부산   20000.0    25000.0
2     3  광주       NaN    35000.0
3     3  대전   30000.0        NaN


12

In [41]:
data12_1 = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}
df12_1 = pd.DataFrame(data12_1)

print(df12_1.isna().sum())

이름    1
나이    1
성별    1
dtype: int64


In [42]:
data12_2 = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}
df12_2 = pd.DataFrame(data12_2)

df12_2 = df12_2.dropna()
print(df12_2)

    이름    나이 성별
0  홍길동  25.0  남


In [43]:
data12_3 = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}
df12_3 = pd.DataFrame(data12_3)

df12_3['나이'] = df12_3['나이'].fillna(df12_3['나이'].mean())
print(df12_3)

    이름         나이   성별
0  홍길동  25.000000    남
1  김철수  27.666667    남
2  NaN  30.000000    여
3  이영희  28.000000  NaN


13

In [44]:
data13_1 = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}
df13_1 = pd.DataFrame(data13_1)

df13_1 = df13_1.pivot(index='날짜', columns='제품', values='판매량')
print(df13_1)

제품            A    B
날짜                  
2024-01-01  100  200
2024-01-02  150  250


In [45]:
data13_2 = {
    '카테고리': ['전자', '가전', '전자', '가전'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}
df13_2 = pd.DataFrame(data13_2)

df13_2 = df13_2.pivot_table(index='카테고리', columns='제품', values='판매량', aggfunc='sum')
print(df13_2)

제품        A      B
카테고리              
가전      NaN  450.0
전자    250.0    NaN


In [46]:
data13_3 = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250],
    '이익': [20, 50, 30, 60]
}
df13_3 = pd.DataFrame(data13_3)

df13_3 = df13_3.pivot(index='날짜', columns='제품', values=['판매량', '이익'])
print(df13_3)

            판매량       이익    
제품            A    B   A   B
날짜                          
2024-01-01  100  200  20  50
2024-01-02  150  250  30  60


14

In [47]:
data14_1 = {
    '이름': ['김철수', '이영희', '김철수', '박민수'],
    '나이': [25, 30, 25, 40],
    '성별': ['남', '여', '남', '남']
}
df14_1 = pd.DataFrame(data14_1)

df14_1 = df14_1.drop_duplicates()
print(df14_1)

    이름  나이 성별
0  김철수  25  남
1  이영희  30  여
3  박민수  40  남


In [54]:
data14_2 = {
    '제품': ['노트북', '태블릿', '노트북', '스마트폰'],
    '가격': [1500000, 800000, 1500000, 1000000],
    '카테고리': ['전자기기', '전자기기', '전자기기', '전자기기']
}
df14_2 = pd.DataFrame(data14_2)
df14_2 = df14_2.drop_duplicates(subset=['제품'])
print("중복 제거 후 데이터:\n", df14_2)
print("행별 중복 여부 체크:\n", df14_2.duplicated())

중복 제거 후 데이터:
      제품       가격  카테고리
0   노트북  1500000  전자기기
1   태블릿   800000  전자기기
3  스마트폰  1000000  전자기기
행별 중복 여부 체크:
 0    False
1    False
3    False
dtype: bool


In [53]:
data14_3 = {
    '학생': ['김민수', '박지현', '김민수', '이정훈'],
    '성적': [90, 85, 90, 88],
    '학교': ['A고', 'B고', 'A고', 'C고']
}
df14_3 = pd.DataFrame(data14_3)
df14_3 = df14_3.drop_duplicates(keep=False)
df14_3.to_csv('df14_3.csv', index=False)

df14_3 = pd.read_csv('df14_3.csv')
print(df14_3)

    학생  성적  학교
0  박지현  85  B고
1  이정훈  88  C고


15

In [50]:
data15_1 = pd.Series(["HELLO", "WORLD", "PYTHON", "PANDAS"])

data15_1 = data15_1.str.lower()
print(data15_1)

0     hello
1     world
2    python
3    pandas
dtype: str


In [51]:
df15_2 = pd.DataFrame({"이름": [" John Doe ", "Alice ", " Bob", "Charlie Doe "]})

df15_2['이름'] = df15_2['이름'].str.strip()
df15_2 = df15_2[df15_2['이름'].str.contains("Doe")]
print(df15_2)

            이름
0     John Doe
3  Charlie Doe


In [52]:
df15_3 = pd.DataFrame({"설명": ["빅데이터 분석", "데이터 과학", "머신 러닝", "딥 러닝"]})

df15_3['약어'] = df15_3['설명'].str.split().srv = df15_3['설명'].str.split().apply(lambda x: "".join([word[0] for word in x]))
print(df15_3)

        설명  약어
0  빅데이터 분석  빅분
1   데이터 과학  데과
2    머신 러닝  머러
3     딥 러닝  딥러
